organization:
  name: # Your name (eg. Open Whisper Systems)
  donationUrl: # A Coinbase link where you can receive donations (eg. https://coinbase.com/checkouts/d29fd4c37ca442393e32fdcb95304701)

github:
  user: # Your BitHub instance's GitHub username.
  token: # Your BitHub instance's GitHub auth token.

  webhook:
    password: # HTTP basic auth. The username defaults to "bithub".

  repositories: # A list of repository URLs to support payouts for.
    - url: # A repository's URL
      mode: # Either MONEYMONEY (default) or FREEBIE.
            # The former will pay out on every commit, unless
            # FREEBIE is specified in the message.  The latter will
            # only pay out if MONEYMONEY is specified in the message.

coinbase:
  apiKey: # Your Coinbase API key.
  apiSecret: # Your Coinbase API secret.

database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the username
  user: pg-user

  # the password
  password: iAMs00perSecrEET

  # the JDBC URL
  url: jdbc:postgresql://db.example.com/db-prod

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyService Health Check */ SELECT 1"

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

  # the amount of time to sleep between runs of the idle connection validation, abandoned cleaner and idle pool resizing
  evictionInterval: 10s

  # the minimum amount of time an connection must sit idle in the pool before it is eligible for eviction
  minIdleTime: 1 minute
